version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: asafebelo/sistema-web-api-backend:latest
    container_name: flask_api
    environment:
      DB_HOST: db
      DB_NAME: meubanco
      DB_USER: user
      DB_PASS: password
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: asafebelo/sistema-web-api-frontend:latest
    container_name: simple_frontend
    environment:
      API_URL: "http://backend:5000"
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
