version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d meubanco"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: asafebelo/sistema-web-api-backend:latest
    container_name: flask_api
    environment:
      DB_HOST: db
      DB_NAME: meubanco
      DB_USER: user
      DB_PASS: password
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    image: asafebelo/sistema-web-api-frontend:latest
    container_name: simple_frontend
    environment:
      API_URL: "http://localhost:5000"
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
